export { default as BootstrapLogo } from './BootstrapLogo'
export { default as AdobephotoshopLogo } from './AdobephotoshopLogo'
export { default as CssLogo } from './CssLogo'
export { default as GitLogo } from './GitLogo'
export { default as HtmlLogo } from './HtmlLogo'
export { default as JavaScriptLogo } from './JavaScriptLogo'
export { default as NextJsLogo } from './NextJsLogo'
export { default as NodeJsLogo } from './NodeJsLogo'
export { default as ReactJsLogo } from './ReactJsLogo'
export { default as TypeScriptLogo } from './TypeScriptLogo'
export { default as WordPressLogo } from './WordPressLogo'
export { default as MySqlLogo } from './MySqlLogo'
export { default as NestJsLogo } from './NestJsLogo'
export { default as TailwindCSSLogo } from './TailwindCSSLogo'
export { default as PostgreSQLLogo } from './PostgreSQLLogo'
export { default as PythonLogo } from './PythonLogo'

export { default as GithubLogo } from './GithubLogo'
export { default as GoToWebsiteLogo } from './GoToWebsiteLogo'

export { default as LinkedinLogo } from './LinkedinLogo'
export { default as MailLogo } from './MailLogo'
export { default as CvIcon } from './CvIcon'