export { default as PortfolioPhoto } from './portfolio.png'
export { default as BadfairyPhoto } from './badfairy.png'
export { default as BingoPhoto } from './bingo.png'
export { default as ApiRedPhoto } from './api-red.png'
export { default as CoveritPhoto } from './coverit.png'